"""empty message

Revision ID: 168b0153aebc
Revises: 8616fc1a0fa9
Create Date: 2025-03-02 16:20:47.458269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168b0153aebc'
down_revision: Union[str, None] = '8616fc1a0fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_attr', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'image_attr')
    # ### end Alembic commands ###
