"""empty message

Revision ID: 8616fc1a0fa9
Revises: 108ea8ebcaf7
Create Date: 2025-03-02 15:38:41.754849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8616fc1a0fa9'
down_revision: Union[str, None] = '108ea8ebcaf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_metadata', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('analysis_result', sa.JSON(), nullable=True))
    op.drop_column('images', 'width')
    op.drop_column('images', 'depth')
    op.drop_column('images', 'time_frames')
    op.drop_column('images', 'height')
    op.drop_column('images', 'channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('channels', sa.INTEGER(), nullable=True))
    op.add_column('images', sa.Column('height', sa.INTEGER(), nullable=True))
    op.add_column('images', sa.Column('time_frames', sa.INTEGER(), nullable=True))
    op.add_column('images', sa.Column('depth', sa.INTEGER(), nullable=True))
    op.add_column('images', sa.Column('width', sa.INTEGER(), nullable=True))
    op.drop_column('images', 'analysis_result')
    op.drop_column('images', 'image_metadata')
    # ### end Alembic commands ###
